# Generated by Django 2.1.2 on 2018-10-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20)),
                ('weather', models.CharField(max_length=20)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind', models.CharField(max_length=20)),
                ('data_update_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=0, null=True)),
            ],
            options={
                'db_table': 'p_weather',
            },
        ),
    ]
