spring:
  application:
    name: project-web
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://118.25.197.159:3306/project?useUnicode=true&characterEncoding=utf8
    username: root
    password: dlf123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 300
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
server:
  port: 8081
  context-path: /project-web
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  path: /data/logs
  file: home.log
